[package]
name = "rstat"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.40", features = ["derive"] }
prettytable = "0.10.0"
strum = { version = "0.27", features = ["derive"] }
tabled = "0.20.0"
